#!/bin/bash

red='\e[1;31m%s\e[0m\n'
green='\e[1;32m%s\e[0m\n'
yellow='\e[1;33m%s\e[0m\n'

BINDIR="/usr/local/bin/"
DIR="$1"

function chklnk() {
for LINK in $(ls $BINDIR) ; do
  if [ -L "${BINDIR}${LINK}" ] ; then
    if [ -e "${BINDIR}${LINK}" ] ; then
      printf $green "Good link "
    else
      printf $red "Broken link "
    fi
  elif [ -e "${BINDIR}${LINK}" ] ; then
    printf $yellow "Not a link "
  else
    printf $yellow "Missing "
  fi
  echo -e "$BINDIR$LINK\n"
done
}

function mklnk() {
  LNKNAME=$(basename $DIR)
  sudo ln -s "$DIR" "${BINDIR}${LNKNAME}"
}

case $@ in
  "") chklnk ;;
  *) mklnk ;;
esac
