#!/bin/bash

red='\e[1;31m%s\e[0m\n'
green='\e[1;32m%s\e[0m\n'
yellow='\e[1;33m%s\e[0m\n'

BINDIR="/usr/local/bin/"
DIR="$2"

function chklnk() {
for LINK in $(ls $BINDIR) ; do
  if [ -L "${BINDIR}${LINK}" ] ; then
    if [ -e "${BINDIR}${LINK}" ] ; then
      printf $green "Good link "
    else
      printf $red "Broken link "
    fi
  elif [ -e "${BINDIR}${LINK}" ] ; then
    printf $yellow "Not a link "
  else
    printf $yellow "Missing "
  fi
  echo -e "$BINDIR$LINK\n"
done
}

function mklnk() {
  LNKNAME=$(basename $DIR) && \
  sudo ln -s "$DIR" "${BINDIR}${LNKNAME}" && \
  printf $green "${LNKNAME} Configured" || printf $red "Error Configuring ${LNKNAME}"
}

function rmlnk() {
  sudo rm -rf ${BINDIR}${DIR} && printf $red "${DIR} Removed" || printf $yellow "Error Removing ${DIR}"
}

case $1 in
  "") chklnk ;;
  -m|--make) mklnk ;;
  -r|--remove) rmlnk ;;
esac
